import { css } from 'zero-css';

// Static styles defined outside component for SSR compatibility
const footerStyles = css({
  marginTop: '4rem',
  padding: '2rem 1rem',
  background: 'linear-gradient(45deg, #2c3e50 0%, #34495e 100%)',
  color: 'white',
  borderRadius: '12px',
  textAlign: 'center',
  boxShadow: '0 -4px 20px rgba(0,0,0,0.1)',
});

const titleStyles = css({
  fontSize: '1.5rem',
  fontWeight: '600',
  marginBottom: '1rem',
  background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  WebkitBackgroundClip: 'text',
  WebkitTextFillColor: 'transparent',
  backgroundClip: 'text',
});

const descriptionStyles = css({
  fontSize: '1rem',
  opacity: '0.9',
  lineHeight: '1.6',
  marginBottom: '1.5rem',
  maxWidth: '600px',
  margin: '0 auto 1.5rem',
});

const badgeContainerStyles = css({
  display: 'flex',
  justifyContent: 'center',
  gap: '1rem',
  flexWrap: 'wrap',
});

const badgeStyles = css({
  background: 'rgba(255, 255, 255, 0.1)',
  backdropFilter: 'blur(10px)',
  padding: '0.5rem 1rem',
  borderRadius: '20px',
  fontSize: '0.85rem',
  fontWeight: '500',
  border: '1px solid rgba(255, 255, 255, 0.2)',
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
  transition: 'transform 0.2s ease',
  '&:hover': {
    transform: 'translateY(-1px)',
  },
});

// Server Component to test zero-css SSR compatibility
export default function ServerFooter() {

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <footer className={footerStyles}>
      <h3 className={titleStyles}>
        ⚡ Zero-CSS SSR Demo
      </h3>
      
      <p className={descriptionStyles}>
        This footer is server-side rendered using Next.js App Router with React Server Components.
        All styles are generated by zero-css during build time for optimal performance.
      </p>
      
      <div className={badgeContainerStyles}>
        <div className={badgeStyles}>
          🖥️ Server Rendered
        </div>
        <div className={badgeStyles}>
          ⚛️ React Server Components
        </div>
        <div className={badgeStyles}>
          🎨 Zero-CSS Styling
        </div>
        <div className={badgeStyles}>
          📅 {currentDate}
        </div>
      </div>
    </footer>
  );
}